apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: actuator
spec:
  version: {{ .TagName }}
  homepage: https://github.com/deviceinsight/kubectl-actuator
  shortDescription: Interact with Spring Boot Actuator endpoints.
  description: |
    This plugin allows you to interact with Spring Boot Actuator endpoints. You can use it to view and modify log levels, view scheduled tasks, and more.
    Examples:
      # Show loggers and their log levels
      kubectl actuator --pod my-app-pod logger
      # Set log level
      kubectl actuator --pod my-app-pod logger com.example.app.service DEBUG
      # View scheduled tasks
      kubectl actuator --deployment my-app scheduled-tasks
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/deviceinsight/kubectl-actuator/releases/download/{{ .TagName }}/kubectl-actuator_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-actuator
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/deviceinsight/kubectl-actuator/releases/download/{{ .TagName }}/kubectl-actuator_Darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-actuator
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/deviceinsight/kubectl-actuator/releases/download/{{ .TagName }}/kubectl-actuator_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-actuator
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/deviceinsight/kubectl-actuator/releases/download/{{ .TagName }}/kubectl-actuator_Windows_x86_64.zip" .TagName | indent 6 }}
      bin: kubectl-actuator.exe